
version: "{build}"

image: Visual Studio 2019

environment:
  global:
    R_VERSION: release

install:
  - choco install r.project -y
  - choco install rtools -y

  - set "PATH=C:\Program Files\R\R-%R_VERSION%\bin;C:\rtools45\ucrt64\bin;C:\rtools45\usr\bin;%PATH%"

  - Rscript -e "R.version.string"

  - Rscript -e "install.packages('remotes')"
  - Rscript -e "remotes::install_deps(dependencies = TRUE)"

artifacts:
  - path: '*.tar.gz'
    name: Package
