
version: "{build}"

image: Visual Studio 2019

environment:
  global:
    R_VERSION: release

install:
  - choco install r.project -y
  - choco install rtools -y
  - set PATH=C:\Program Files\R\R-%R_VERSION%\bin;%PATH%
  - Rscript -e "install.packages('remotes')"
  - Rscript -e "remotes::install_deps(dependencies = TRUE)"

build_script:
  - Rscript -e "devtools::install()"
  - Rscript -e "devtools::check(error_on = 'warning')"

artifacts:
  - path: '*.tar.gz'
    name: Package
