# AppVeyor config
version: "{build}"
image: Visual Studio 2019

environment:
  global:
    R_VERSION: release
    PATH: "C:\\Program Files\\R\\R-%R_VERSION%\\bin;C:\\rtools45\\ucrt64\\bin;C:\\rtools45\\usr\\bin;%PATH%"

init:
  - echo %PATH%

install:
  - choco install r.project -y

  - choco install rtools -y

  - refreshenv

  - Rscript -e "R.version.string"

  - Rscript -e "install.packages('remotes')"
  - Rscript -e "remotes::install_deps(dependencies = TRUE)"
  - Rscript -e "install.packages(c('sf','terra','raster'), type='binary')"

build_script:
  - Rscript -e "devtools::install()"
  - Rscript -e "devtools::check(error_on = 'warning')"

artifacts:
  - path: '*.tar.gz'
    name: Package
