#' @title Convert SpatRaster to RasterLayer
#' @description Converts a SpatRaster object to a RasterLayer object.
#' @param spat_raster A SpatRaster object.
#' @return A RasterLayer object.
#' @export
spat_to_raster <- function(spat_raster) {
  as(spat_raster, "Raster")
}

#' @title Convert RasterLayer to SpatRaster
#' @description Converts a RasterLayer object to a SpatRaster object.
#' @param raster_layer A RasterLayer object.
#' @return A SpatRaster object.
#' @export
raster_to_spat <- function(raster_layer) {
  rast(raster_layer)
}

#' @title Calculate Habitat Changes Between Two Rasters
#' @description Compares two binary raster files and generates a new raster highlighting areas of gain, loss, stability, and absence. This function is specifically designed for comparing habitat changes between two time points or scenarios.
#' @param raster1 A SpatRaster or RasterLayer object representing the first habitat map.
#' @param raster2 A SpatRaster or RasterLayer object representing the second habitat map.
#' @return A RasterLayer object representing the habitat changes.
#' @details hb_changes function ensures both input rasters are in the same CRS and extent, computes the differences, and generates a new raster with categories for gain (green), loss (red), stability (yellow), and absence (gray). It is useful for ecological and environmental studies to visualize how habitats have changed over time or under different conditions.
#' @examples
#' # Load sample rasters
#' raster1 <- rast("path/to/first_raster.tif")
#' raster2 <- rast("path/to/second_raster.tif")
#'
#' # Convert to binary
#' raster1_binary <- hb_binary(raster1, th = 0.5)
#' raster2_binary <- hb_binary(raster2, th = 0.5)
#'
#' # Calculate changes
#' changes_raster <- hb_changes(raster1_binary, raster2_binary)
#'
#' # Plot changes
#' hb_plot_changes(changes_raster)
#' @export
hb_changes <- function(raster1, raster2) {
  if (inherits(raster1, "SpatRaster")) {
    raster1 <- spat_to_raster(raster1)
  }
  if (inherits(raster2, "SpatRaster")) {
    raster2 <- spat_to_raster(raster2)
  }

  if (!inherits(raster1, "RasterLayer") || !inherits(raster2, "RasterLayer")) {
    stop("Both inputs must be RasterLayer objects.")
  }

  if (!compareCRS(raster1, raster2)) {
    raster2 <- projectRaster(raster2, crs(raster1))
  }
  if (!identical(extent(raster1), extent(raster2))) {
    raster2 <- resample(raster2, raster1)
  }

  # Calculate changes
  changes <- overlay(raster1, raster2, fun = function(x1, x2) {
    ifelse(x1 == 1 & x2 == 0, 1,  # loss
           ifelse(x1 == 0 & x2 == 1, 2,  # gain
                  ifelse(x1 == 1 & x2 == 1, 3,  # stable
                         ifelse(x1 == 0 & x2 == 0, 4, NA))))  # absence
  })

  levels(changes) <- data.frame(ID = 1:4, category = c("Loss", "Gain", "Stable", "Absent"))

  return(changes)
}

library(raster)
library(ggplot2)

#' @title Plot Habitat Changes
#' @description Plots a raster highlighting areas of habitat gain, loss, stability, and absence. This visualization helps in understanding the extent and distribution of habitat changes.
#' @param changes_raster A RasterLayer object generated by `hb_changes`.
#' @param title Optional. Title of the plot. Default is "Changes".
#' @param xlab Optional. Label for the x-axis. Default is "Longitude".
#' @param ylab Optional. Label for the y-axis. Default is "Latitude".
#' @param bg_color Optional. Background color of the plot. Default is "white".
#' @details This function plots the habitat changes using ggplot2, with colors representing different types of changes. It provides a visual representation of how habitats have changed, which is useful for ecological assessments and decision-making.
#' @examples
#' # Load sample rasters
#' raster1 <- raster("path/to/first_raster.tif")
#' raster2 <- raster("path/to/second_raster.tif")
#'
#' # Convert to binary
#' raster1_binary <- hb_binary(raster1, th = 0.5)
#' raster2_binary <- hb_binary(raster2, th = 0.5)
#'
#' # Calculate changes
#' changes_raster <- hb_changes(raster1_binary, raster2_binary)
#'
#' # Plot changes
#' hb_plot_changes(changes_raster, title = "Habitat Changes", xlab = "X Axis", ylab = "Y Axis", bg_color = "lightgray")
#' @export
hb_plot_changes <- function(changes_raster, title = "Changes", xlab = "Longitude", ylab = "Latitude", bg_color = "white") {
  # Convert RasterLayer to data frame for ggplot2
  changes_df <- as.data.frame(rasterToPoints(changes_raster), stringsAsFactors = TRUE)
  colnames(changes_df) <- c("x", "y", "category")
  changes_df$category <- factor(changes_df$category, levels = 1:4, labels = c("Loss", "Gain", "Stable", "Absent"))
  
  # Round coordinates to reduce floating-point precision issues
  changes_df$x <- round(changes_df$x, 6)
  changes_df$y <- round(changes_df$y, 6)
  
  # Use cell size to set tile width/height and avoid gaps or shifting
  res_vals <- res(changes_raster)
  resx <- res_vals[1]
  resy <- res_vals[2]

  ggplot() +
    geom_tile(data = changes_df, aes(x = x, y = y, fill = category),
              width = resx, height = resy, color = NA) +
    scale_fill_manual(values = c("Loss" = "red", "Gain" = "green", "Stable" = "yellow", "Absent" = "gray"), name = "Change") +
    theme_minimal() +
    labs(title = title, x = xlab, y = ylab) +
    coord_fixed(expand = FALSE) +
    theme(panel.background = element_rect(fill = bg_color, color = NA))
}
