library(terra)

#' @title Convert SpatRaster to RasterLayer
#' @description Converts a SpatRaster object to a RasterLayer object.
#' @param spat_raster A SpatRaster object.
#' @return A RasterLayer object.
#' @export
spat_to_raster <- function(spat_raster) {
  as(spat_raster, "Raster")
}

#' @title Convert RasterLayer to SpatRaster
#' @description Converts a RasterLayer object to a SpatRaster object.
#' @param raster_layer A RasterLayer object.
#' @return A SpatRaster object.
#' @export
raster_to_spat <- function(raster_layer) {
  rast(raster_layer)
}

#' @title Calculate Habitat Changes Between Two Rasters
#' @description Compares two binary raster files and generates a new raster highlighting areas of gain, loss, stability, and absence. This function is specifically designed for comparing habitat changes between two time points or scenarios.
#' @param raster1 A SpatRaster or RasterLayer object representing the first habitat map.
#' @param raster2 A SpatRaster or RasterLayer object representing the second habitat map.
#' @return A SpatRaster object representing the habitat changes.
#' @details hb_changes ensures both input rasters are in the same CRS and extent, computes the differences, and generates a new raster with categories for gain (green), loss (red), stability (yellow), and absence (gray). It is useful for ecological and environmental studies to visualize how habitats have changed over time or under different conditions.
#' @examples
#' # Load sample rasters
#' raster1 <- rast("path/to/first_raster.tif")
#' raster2 <- rast("path/to/second_raster.tif")
#'
#' # Convert to binary
#' raster1_binary <- hb_binary(raster1, th = 0.5)
#' raster2_binary <- hb_binary(raster2, th = 0.5)
#'
#' # Calculate changes
#' changes_raster <- hb_changes(raster1_binary, raster2_binary)
#'
#' # Plot changes
#' hb_plot_changes(changes_raster)
#' @export
hb_changes <- function(raster1, raster2) {
  if (inherits(raster1, "RasterLayer")) {
    raster1 <- rast(raster1)
  }
  if (inherits(raster2, "RasterLayer")) {
    raster2 <- rast(raster2)
  }

  if (!inherits(raster1, "SpatRaster") || !inherits(raster2, "SpatRaster")) {
    stop("Both inputs must be SpatRaster or RasterLayer objects.")
  }

  if (!crs(raster1) == crs(raster2)) {
    raster2 <- project(raster2, raster1)
  }
  if (!all.equal(ext(raster1), ext(raster2))) {
    raster2 <- resample(raster2, raster1)
  }

  changes <- lapp(c(raster1, raster2), fun = function(x1, x2) {
    ifelse(x1 == 1 & x2 == 0, 1,  # loss
           ifelse(x1 == 0 & x2 == 1, 2,  # gain
                  ifelse(x1 == 1 & x2 == 1, 3,  # stable
                         ifelse(x1 == 0 & x2 == 0, 4, NA))))  # absence
  })

  # Add category labels (terra)
  categories(changes) <- data.frame(value = 1:4,
                                    category = c("Loss", "Gain", "Stable", "Absent"))

  return(changes)
}


#' @title Plot Habitat Changes (terra)
#' @description Plots a SpatRaster highlighting areas of habitat gain, loss, stability, and absence using terra's native plotting.
#' @param changes_raster A SpatRaster object generated by `hb_changes`.
#' @param title Optional. Title of the plot. Default is "Changes".
#' @param bg_color Optional. Background color of the plot. Default is "white".
#' @details Uses terra::plot() for fast, seam-free visualization of rasters.
#' @examples
#' changes_raster <- hb_changes(raster1_binary, raster2_binary)
#' hb_plot_changes(changes_raster, title = "Habitat Changes")
#' @export
hb_plot_changes <- function(changes_raster, title = "Changes", bg_color = "white") {
  if (inherits(changes_raster, "RasterLayer")) {
    changes_raster <- rast(changes_raster)
  }
  plot(changes_raster,
       col = c("red", "green", "yellow", "gray"),
       main = title,
       axes = TRUE,
       type = "classes",
       plg = list(title = "Change"),
       mar = c(4, 4, 4, 8),
       colNA = bg_color)
}
