# Load necessary libraries
library(sdm)

#' @title Extract Evaluation Metrics from sdmModels Object
#' @description Extracts evaluation metrics including threshold, sensitivity, specificity, TSS, MCC, F1, Kappa, NMI, PHI, PPV, NPV, CCR, MCR, Omission, Commission, and Prevalence from a trained sdm model.
#' @param sdm_model An sdmModels object generated by the sdm function.
#' @return A data frame with evaluation metrics.
#' @examples
#' # Assume that the user has already trained their model and wants to extract the
#'  #threshold value based on metrics such as sensitivity (sp), specificity (se), max(sp + se),
#'  #kappa, positive predictive value (ppv), negative predictive value (npv),
#'  #normalized mutual information (nmi), correct classification rate (ccr), prevalence,
#'  #and specific percentages (P10, P5, P1, P0).
#'
#'  library(sdm)
#' # sdm_model <- trained_model_object
#'
#' # Extract evaluation metrics
#' eval_metrics <- hb_ext_eval(sdm_model)
#' print(eval_metrics)
#' @references
#' Ghasemian Sorboni, S., Hadipour, M., & Pourebrahim, S (2024). habitat: An R Package for Analyzing and Comparing Habitat Changes. dataset. doi:.

#' @export
hb_ext_eval <- function(sdm_model) {
  if (!inherits(sdm_model, "sdmModels")) {
    stop("The input must be an sdmModels object.")
  }

  # Extract evaluation metrics
  eval_metrics <- getEvaluation(sdm_model, stat = c(
    'threshold', 'sensitivity', 'specificity', 'TSS', 'MCC', 'F1', 'Kappa', 'NMI', 'PHI', 'PPV', 'NPV',
    'CCR', 'MCR', 'Omission', 'Commission', 'Prevalence'
  ))

  return(eval_metrics)
}

#' @title Calculate Optimal Thresholds from Evaluation Metrics
#' @description Calculates various optimal thresholds based on different criteria such as max(sp + se), max(kappa), and others.
#' @param eval_metrics A data frame with evaluation metrics.
#' @return A list with optimal thresholds for different criteria.
#' @examples
#' # Assuming the user has already extracted evaluation metrics
#' #PLEASE READ hb_ext_eval FIRST
#' # eval_metrics <- hb_ext_eval(sdm_model)
#'
#' # Calculate optimal thresholds
#' thresholds <- hb_opt_th(eval_metrics)
#' print(thresholds)
#'
#' # Example usage of the extracted threshold with existing functions:
#' # max_sp_se_threshold <- thresholds$max_sp_se
#' # binary_map <- hb_binary(r, th = max_sp_se_threshold)
#' # habitat_analysis <- hb_an_habitat(x1, x2, threshold = max_sp_se_threshold)
#' # range_analysis <- hb_range(x, y, th = max_sp_se_threshold)
#' @references
#' Ghasemian Sorboni, S., Hadipour, M., & Pourebrahim, S (2024). habitat: An R Package for Analyzing and Comparing Habitat Changes. dataset. doi:.

#' @export
hb_opt_th <- function(eval_metrics) {
  if (is.null(eval_metrics)) {
    stop("Evaluation metrics cannot be NULL.")
  }

  eval_metrics$SE_SP <- eval_metrics$sensitivity + eval_metrics$specificity

  # Calculate different thresholds
  thresholds <- list(
    max_sp_se = eval_metrics$threshold[which.max(eval_metrics$SE_SP)], # Maximizes the sum of sensitivity and specificity
    sp_se_equal = eval_metrics$threshold[which.min(abs(eval_metrics$sensitivity - eval_metrics$specificity))], # Minimizes the difference between sensitivity and specificity
    min_cost = eval_metrics$threshold[which.min(eval_metrics$sensitivity + (1 - eval_metrics$specificity))], # Minimizes the cost (combination of sensitivity and specificity)
    max_kappa = eval_metrics$threshold[which.max(eval_metrics$Kappa)], # Maximizes Cohen's kappa
    max_ppv_npv = eval_metrics$threshold[which.max(eval_metrics$PPV + eval_metrics$NPV)], # Maximizes the sum of positive predictive value (PPV) and negative predictive value (NPV)
    ppv_equal_npv = eval_metrics$threshold[which.min(abs(eval_metrics$PPV - eval_metrics$NPV))], # Minimizes the difference between PPV and NPV
    max_nmi = eval_metrics$threshold[which.max(eval_metrics$NMI)], # Maximizes normalized mutual information (NMI)
    max_ccr = eval_metrics$threshold[which.max(eval_metrics$CCR)], # Maximizes correct classification rate (CCR)
    prevalence = eval_metrics$threshold[which.min(abs(eval_metrics$Prevalence - eval_metrics$specificity))], # Minimizes the difference between prevalence and specificity
    P10 = eval_metrics$threshold[which.min(abs(eval_metrics$Prevalence - 0.10))], # Minimizes the difference between prevalence and 10%
    P5 = eval_metrics$threshold[which.min(abs(eval_metrics$Prevalence - 0.05))], # Minimizes the difference between prevalence and 5%
    P1 = eval_metrics$threshold[which.min(abs(eval_metrics$Prevalence - 0.01))], # Minimizes the difference between prevalence and 1%
    P0 = eval_metrics$threshold[which.min(abs(eval_metrics$Prevalence - 0.00))] # Minimizes the difference between prevalence and 0%
  )

  return(thresholds)
}

