name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        install.packages(c("devtools", "pkgdown"))

    - name: Build HTML documentation
      run: |
        Rscript -e 'pkgdown::build_site()'
     
    - name: Convert Rd files to PDF
      run: |
        R CMD Rd2pdf --output=docs/package.pdf .
     
    - name: Upload HTML documentation
      uses: actions/upload-artifact@v2
      with:
        name: html-docs
        path: docs/

    - name: Upload PDF documentation
      uses: actions/upload-artifact@v2
      with:
        name: pdf-docs
        path: docs/package.pdf
